### ISSUE TITLE
Left align mode - Clicking on last slide unexpectedly sets first slide as active

### ISSUE THREAD

**Issue by jasonpilbrough** [VagrantAI-c/ng-carousel-cdk#163]
Example (replicated on https://vagrantai-c.github.io/ng-carousel-cdk/):

https://github.com/VagrantAI-c/ng-carousel-cdk/assets/53018790/2eaea33c-d978-46b1-aa48-10c0cc2ed324

**Current behaviour:**
When slide 3 is the active slide, clicking on slide 3 changes the active slide back to slide 1.

**Expected behvaiour:**
When slide 3 is the active slide, clicking on slide 3 should not change the active slide.

**Parameters used in above example:**
Align mode: To the left
Width mode: In percent
Fill empty space: Do not fill
Slide width: 38%
Autoplay: Off

**Comment by VagrantAI-c** [comment]
Hello and thank you for your report. I can reproduce this behavior and will look now into it

**Comment by jasonpilbrough** [comment]
Thank you so much!

Kind regards,
Jason
